myfile=open("hello.txt","w")
myfile.write("ICTA calicut fullstack class")
myfile.close()
print("file created")
myfile2=open("hello.txt","r")
print("file read")
s=myfile2.read()
print(s)
myfile2.close()