def Employeedata():
    employeedata=[
        {
            'id':1,
            'name':'raad',
            'place':'idukki',
            'mobile':'56478654',
            'email':'raad@gmail.com',
            'joineddate':'06/10/2018',
            'salary':12000
        },
        {
            'id':2,
            'name':'mili',
            'place':'mahe',
            'mobile':'98547612',
            'email':'mili@gmail.com',
            'joineddate':'08/10/2018',
            'salary':13000
        },
        {
            'id':3,
            'name':'mithun',
            'place':'calicut',
            'mobile':'98745621',
            'email':'mithun@gmail.com',
            'joineddate':'02/10/2018',
            'salary':14000
        },
        {
            'id':4,
            'name':'krithi',
            'place':'alapi',
            'mobile':'7558469233',
            'email':'krithi@gmail.com',
            'joineddate':'04/10/2018',
            'salary':14000

        },
        {
            'id':5,
            'name':'arvind',
            'place':'calicut',
            'mobile':'7895684152',
            'email':'arvind@gmail.com',
            'joineddate':'11/10/2018',
            'salary':14000
        },
        {
            'id':6,
            'name':'rada',
            'place':'vadakara',
            'mobile':'9874563215',
            'email':'rada@gmail.com',
            'joineddate':'06/10/2018',
            'salary':14000
        },
        {
            'id':7,
            'name':'varun',
            'place':'kochi',
            'mobile':'7895641236',
            'email':'varun@gmail.com',
            'joineddate':'06/10/2018',
            'salary':14000
        },
        {
            'id':8,
            'name':'hrithu',
            'place':'kannur',
            'mobile':'7558921475',
            'email':'hrithu30@gmail.com',
            'joineddate':'06/10/2018',
            'salary':25000
        },
        {
            'id':9,
            'name':'sulu',
            'place':'kannu',
            'mobile':'4569',
            'email':'sulu@dfrgtg',
            'joineddate':'12/10/2015',
            'salary':17895
        },
        {
            'id':10,
            'name':'gokul',
            'place':'thrissur',
            'mobile':'894578996',
            'email':'gokul@gmail.com',
            'joineddate':'09/10/2018',
            'salary':17850
        }
        
    ]
    return employeedata
    
    